project:
  type: website

execute:
  freeze: auto

website:
  title: "Erick Pound"
  navbar:
    right:
      - about.qmd
      # - text: reviews
      #   href: reviews/index.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: lux
    css: styles.css
