baseURL = 'https://ejrp.me/'
languageCode = 'en-us'
title = 'EJRP'
theme = 'PaperMod'

[pagination]
  pagerSize = 5

[params]
  env = "production"
  title = "EJRP"
  description = "Personal website and blog"
  keywords = ["Blog", "Portfolio", "Personal"]
  author = "Erick Pound"
  images = [""]
  DateFormat = "January 2, 2006"
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.assets]
    disableHLJS = false
    disableFingerprinting = false

  [params.label]
    text = "Home"
    icon = ""
    iconHeight = 35

  [params.profileMode]
    enabled = false
    title = "EJRP"
    subtitle = "Welcome to my personal site"
    imageUrl = ""
    imageWidth = 120
    imageHeight = 120
    imageTitle = ""

    [[params.profileMode.buttons]]
      name = "Posts"
      url = "posts"

    [[params.profileMode.buttons]]
      name = "About"
      url = "about"

  [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = "Welcome to my personal website and blog."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Writing"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 30

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "github"
